# Generated by Django 4.2 on 2023-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vaikom_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaikom',
            name='time_format',
            field=models.CharField(max_length=100),
        ),
    ]
